branches:
  only:
    - master
dependencies:
  pre:
    - xcrun instruments -w 'iPhone 7 (11.0)' || sleep 15
matrix:
  include:
    - os: osx
      osx_image: xcode9
      language: swift
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION="4.0"
        - SWIFTENV_ROOT="$HOME/.swiftenv"
        - PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="EntropyString"
install: ./ci/install.sh
script: ./ci/travis.sh
