matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      language: swift
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="EntropyString"
install: ./ci/install.sh
script: ./ci/travis.sh
